substitutions:
  name: ecan-e02-mdio-scan
  friendly_name: ECAN E02 MDIO Scan
  mdc_pin: GPIO18
  mdio_pin: GPIO5
  reset_pin: GPIO14
  phy_addr_start: "0"
  phy_addr_end: "31"
  phy_addr_batch_size: "1"

packages:
  bare: !include ecan-e02-bare.yaml

esphome:
  build_path: build/ecan-e02-ethernet-mdio-scan

ecan_e02:
  id: board
  update_interval: 1s
  mdio_scan:
    mdc_pin: ${mdc_pin}
    mdio_pin: ${mdio_pin}
    phy_addr_start: ${phy_addr_start}
    phy_addr_end: ${phy_addr_end}
    phy_addr_batch_size: ${phy_addr_batch_size}
    reset_pin: ${reset_pin}
    reset_active_low: true
    reset_hold_ms: 10
    reset_settle_ms: 100
