substitutions:
  name: ecan-e02
  friendly_name: Ebyte ECAN E02
  name_add_mac_suffix: "true"

packages:
  ecan_e02: github://EiNSTeiN-/esphome-ecan-e02/packages/ecan-e02-base.yaml@main

external_components:
  - source: github://EiNSTeiN-/esphome-ecan-e02@main
    components: [ecan_e02]
